DELETE http://localhost:3001/api/users/6890cc0eb12066bc8d0a2aa3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OTBjYzBlYjEyMDY2YmM4ZDBhMmFhMyIsInVzZXJuYW1lIjoiTE1BTTE5NzciLCJpYXQiOjE3NTQzMjAxODEsImV4cCI6MTc1NDkyNDk4MX0.hSDIE3pGgk_ZfYypK-owgM98UTJEIilyAvLnBuNVtZw