DELETE http://localhost:3001/api/images/688e1a03845a2dbc47369ed4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OGUxNjRiMDMyN2JkNDRhNjM4NGQ0NiIsInVzZXJuYW1lIjoiamFzYmEyNCIsImlhdCI6MTc1NDE0MjQ5MCwiZXhwIjoxNzU0NzQ3MjkwfQ.Q2XGRoWmLzQXmzSDx7swNvdKfgKbhpne-6MeV5QOTdU